In [50]:
import pandas as pd

df = pd.read_csv("train.csv")

df.head()

,h_0,h_1,h_2,h_3,h_4,h_5,h_6,h_7,h_8,h_9,...,h_20,h_21,h_22,h_23,h_24,h_25,h_26,h_27,h_28,status
0,303.5900,303.4300,305.5100,306.2400,305.3700,305.0600,305.0100,305.4000,306.0000,306.0900,...,304.3900,305.2700,305.880,304.9500,305.2900,304.0400,304.2700,304.3000,305.2500,0.0
1,368.1800,365.7500,361.9900,364.0600,363.1700,363.3000,364.4000,365.5200,363.6700,356.3300,...,359.1100,357.9800,357.410,357.0700,354.6800,353.8000,349.6200,351.6000,354.4700,0.0
2,21.2989,21.3389,21.3376,21.2184,21.0715,21.0046,21.0328,21.0681,21.1238,21.0130,...,21.1085,21.1412,21.127,21.0260,21.0800,21.0868,21.1969,21.0473,21.0621,0.0
3,16.7998,16.8058,16.7182,16.6321,16.6668,16.6284,16.6463,16.4354,16.4730,16.3476,...,16.5478,16.5099,16.425,16.4874,16.4593,16.4595,16.4946,16.5199,16.5218,1.0
4,347.8000,344.3300,342.6800,351.6000,349.6200,359.4300,353.3100,348.1700,348.2800,350.1900,...,331.2700,337.9000,338.990,336.2700,340.1500,343.5000,347.6200,344.6000,347.8300,1.0

In [44]:
test = pd.read_csv("test_soal.csv")
test.head()

,h_0,h_1,h_2,h_3,h_4,h_5,h_6,h_7,h_8,h_9,...,h_19,h_20,h_21,h_22,h_23,h_24,h_25,h_26,h_27,h_28
0,371.1000,373.4000,377.5000,378.7000,378.4000,376.9000,380.1000,382.4000,381.6000,380.2000,...,373.9000,371.8000,372.9000,373.0000,375.0000,376.7000,377.4000,374.9000,377.1000,378.1000
1,21.8002,22.0125,21.8196,21.5034,21.5724,21.9344,21.8135,21.9626,22.9809,22.8522,...,22.3193,22.5838,22.4538,22.2917,22.6930,22.2794,22.7801,22.6797,23.2745,23.6477
2,33.3447,33.1191,33.0849,33.0843,32.9912,32.5786,32.7185,32.4195,32.7812,31.9584,...,32.2980,32.5186,32.6183,33.2084,33.1996,33.5176,33.6696,33.4384,33.4957,33.5986
3,17.0649,17.0520,17.0851,17.1365,17.1532,17.1797,17.1868,17.2131,17.2927,17.2224,...,17.1553,17.1119,17.0754,17.0549,17.0362,17.0211,16.9615,16.9542,16.9350,16.9329
4,318.5130,320.6418,323.6143,327.8755,326.4917,327.4583,327.8121,325.8354,326.6951,321.9228,...,335.9800,337.4390,334.6706,339.9901,349.2000,349.5033,347.3175,341.5232,343.8698,343.1532

In [45]:
print(df.shape)
print(test.shape)

(25174, 30)
(6294, 29)

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25174 entries, 0 to 25173
Data columns (total 30 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   h_0     25174 non-null  float64
 1   h_1     25174 non-null  float64
 2   h_2     25174 non-null  float64
 3   h_3     25174 non-null  float64
 4   h_4     25174 non-null  float64
 5   h_5     25174 non-null  float64
 6   h_6     25174 non-null  float64
 7   h_7     25174 non-null  float64
 8   h_8     25174 non-null  float64
 9   h_9     25174 non-null  float64
 10  h_10    25174 non-null  float64
 11  h_11    25174 non-null  float64
 12  h_12    25174 non-null  float64
 13  h_13    25174 non-null  float64
 14  h_14    25174 non-null  float64
 15  h_15    25174 non-null  float64
 16  h_16    25174 non-null  float64
 17  h_17    25174 non-null  float64
 18  h_18    25174 non-null  float64
 19  h_19    25174 non-null  float64
 20  h_20    25174 non-null  float64
 21  h_21    25174 non-null  float64
 22  h_22    25174 non-null  float64
 23  h_23    25174 non-null  float64
 24  h_24    25174 non-null  float64
 25  h_25    25174 non-null  float64
 26  h_26    25174 non-null  float64
 27  h_27    25174 non-null  float64
 28  h_28    25174 non-null  float64
 29  status  25174 non-null  float64
dtypes: float64(30)
memory usage: 5.8 MB

In [47]:
train = df.values
batas = train.shape[0] * 8 // 10

x = train[:,:-1]
y = train[:,-1]

x_train = x[:batas]
x_test = x[batas:]
y_train = y[:batas]
y_test = y[batas:]

print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(20139, 29)
(5035, 29)
(20139,)
(5035,)

In [48]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression(max_iter = 30000, solver = 'lbfgs')
lr.fit(x_train,y_train)
lr.score(x_train,y_train)

0.5243557276925369

In [49]:
from sklearn.metrics import accuracy_score
y_pred = lr.predict(x_test)
print(accuracy_score(y_pred,y_test))

0.5245283018867924

In [51]:
x_test = test.values
hasil_pred = lr.predict(x_test)

In [52]:
hasil = pd.DataFrame({"status": hasil_pred.ravel()}).astype(int)

hasil.to_csv("2010215.csv", index = False)

In [10]:
hasil.shape

(6294, 1)

In [12]:
from sklearn.model_selection import cross_val_score

crosval = cross_val_score(LogisticRegression(), x_train,y_train, cv=10)

print(crosval.ravel().mean())

C:\Users\Mahasiswa Zeeber\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Mahasiswa Zeeber\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Mahasiswa Zeeber\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Mahasiswa Zeeber\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Mahasiswa Zeeber\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Mahasiswa Zeeber\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Mahasiswa Zeeber\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Mahasiswa Zeeber\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

0.5136484735092579

C:\Users\Mahasiswa Zeeber\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Mahasiswa Zeeber\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [13]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier()
rf.fit(x_train,y_train)
rf.score(x_train,y_train)

1.0

In [14]:


crosval = cross_val_score(RandomForestClassifier(), x_train,y_train, cv=10)

print(crosval.ravel().mean())

0.5546803283279778